/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/matthias/Projekte/heizungssteuerung/dsdl/homeautomation/20009.BathroomStatus.uavcan
 */

#ifndef __HOMEAUTOMATION_BATHROOMSTATUS
#define __HOMEAUTOMATION_BATHROOMSTATUS

#include <stdint.h>
#include "canard.h"

#ifdef __cplusplus
extern "C"
{
#endif

/******************************* Source text **********************************
uint3 brightness
bool door_open
bool person_inside
bool private_mode
bool fan_running
******************************************************************************/

/********************* DSDL signature source definition ***********************
homeautomation.BathroomStatus
saturated uint3 brightness
saturated bool door_open
saturated bool person_inside
saturated bool private_mode
saturated bool fan_running
******************************************************************************/

#define HOMEAUTOMATION_BATHROOMSTATUS_ID                   20009
#define HOMEAUTOMATION_BATHROOMSTATUS_NAME                 "homeautomation.BathroomStatus"
#define HOMEAUTOMATION_BATHROOMSTATUS_SIGNATURE            (0x9327636A236A511CULL)

#define HOMEAUTOMATION_BATHROOMSTATUS_MAX_SIZE             ((7 + 7)/8)

// Constants

typedef struct
{
    // FieldTypes
    uint8_t    brightness;                    // bit len 3
    bool       door_open;                     // bit len 1
    bool       person_inside;                 // bit len 1
    bool       private_mode;                  // bit len 1
    bool       fan_running;                   // bit len 1

} homeautomation_BathroomStatus;

extern
uint32_t homeautomation_BathroomStatus_encode(homeautomation_BathroomStatus* source, void* msg_buf);

extern
int32_t homeautomation_BathroomStatus_decode(const CanardRxTransfer* transfer, uint16_t payload_len, homeautomation_BathroomStatus* dest, uint8_t** dyn_arr_buf);

extern
uint32_t homeautomation_BathroomStatus_encode_internal(homeautomation_BathroomStatus* source, void* msg_buf, uint32_t offset, uint8_t root_item);

extern
int32_t homeautomation_BathroomStatus_decode_internal(const CanardRxTransfer* transfer, uint16_t payload_len, homeautomation_BathroomStatus* dest, uint8_t** dyn_arr_buf, int32_t offset, uint8_t tao);

#ifdef __cplusplus
} // extern "C"
#endif
#endif // __HOMEAUTOMATION_BATHROOMSTATUS