/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/matthias/Projekte/heizungssteuerung/dsdl/homeautomation/20000.Environment.uavcan
 */

#ifndef __HOMEAUTOMATION_ENVIRONMENT
#define __HOMEAUTOMATION_ENVIRONMENT

#include <stdint.h>
#include "canard.h"

#ifdef __cplusplus
extern "C"
{
#endif

/******************************* Source text **********************************
bool humidity_valid
bool pressure_valid
int19 temperature
uint17 humidity
uint18 pressure
******************************************************************************/

/********************* DSDL signature source definition ***********************
homeautomation.Environment
saturated bool humidity_valid
saturated bool pressure_valid
saturated int19 temperature
saturated uint17 humidity
saturated uint18 pressure
******************************************************************************/

#define HOMEAUTOMATION_ENVIRONMENT_ID                      20000
#define HOMEAUTOMATION_ENVIRONMENT_NAME                    "homeautomation.Environment"
#define HOMEAUTOMATION_ENVIRONMENT_SIGNATURE               (0xD5AA9C5110D3749ULL)

#define HOMEAUTOMATION_ENVIRONMENT_MAX_SIZE                ((56 + 7)/8)

// Constants

typedef struct
{
    // FieldTypes
    bool       humidity_valid;                // bit len 1
    bool       pressure_valid;                // bit len 1
    int32_t    temperature;                   // bit len 19
    uint32_t   humidity;                      // bit len 17
    uint32_t   pressure;                      // bit len 18

} homeautomation_Environment;

extern
uint32_t homeautomation_Environment_encode(homeautomation_Environment* source, void* msg_buf);

extern
int32_t homeautomation_Environment_decode(const CanardRxTransfer* transfer, uint16_t payload_len, homeautomation_Environment* dest, uint8_t** dyn_arr_buf);

extern
uint32_t homeautomation_Environment_encode_internal(homeautomation_Environment* source, void* msg_buf, uint32_t offset, uint8_t root_item);

extern
int32_t homeautomation_Environment_decode_internal(const CanardRxTransfer* transfer, uint16_t payload_len, homeautomation_Environment* dest, uint8_t** dyn_arr_buf, int32_t offset, uint8_t tao);

#ifdef __cplusplus
} // extern "C"
#endif
#endif // __HOMEAUTOMATION_ENVIRONMENT