/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 */

#ifndef __HOMEAUTOMATION_GREYWATERPUMPSTATUS
#define __HOMEAUTOMATION_GREYWATERPUMPSTATUS

#include <stdint.h>
#include "canard.h"

#ifdef __cplusplus
extern "C"
{
#endif

/******************************* Source text **********************************
uint8 state
******************************************************************************/

/********************* DSDL signature source definition ***********************
homeautomation.GreywaterPumpStatus
saturated uint8 state
******************************************************************************/

#define HOMEAUTOMATION_GREYWATERPUMPSTATUS_ID              20007
#define HOMEAUTOMATION_GREYWATERPUMPSTATUS_NAME            "homeautomation.GreywaterPumpStatus"
#define HOMEAUTOMATION_GREYWATERPUMPSTATUS_SIGNATURE       (0xF716D32B2A6E8D44ULL)

#define HOMEAUTOMATION_GREYWATERPUMPSTATUS_MAX_SIZE        ((8 + 7)/8)

// Constants

typedef struct
{
    // FieldTypes
    uint8_t    state;                         // bit len 8

} homeautomation_GreywaterPumpStatus;

extern
uint32_t homeautomation_GreywaterPumpStatus_encode(homeautomation_GreywaterPumpStatus* source, void* msg_buf);

extern
int32_t homeautomation_GreywaterPumpStatus_decode(const CanardRxTransfer* transfer, uint16_t payload_len, homeautomation_GreywaterPumpStatus* dest, uint8_t** dyn_arr_buf);

extern
uint32_t homeautomation_GreywaterPumpStatus_encode_internal(homeautomation_GreywaterPumpStatus* source, void* msg_buf, uint32_t offset, uint8_t root_item);

extern
int32_t homeautomation_GreywaterPumpStatus_decode_internal(const CanardRxTransfer* transfer, uint16_t payload_len, homeautomation_GreywaterPumpStatus* dest, uint8_t** dyn_arr_buf, int32_t offset, uint8_t tao);

#ifdef __cplusplus
} // extern "C"
#endif
#endif // __HOMEAUTOMATION_GREYWATERPUMPSTATUS