/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 */
#include "homeautomation/Environment.h"
#include "canard.h"

#ifndef CANARD_INTERNAL_SATURATE
#define CANARD_INTERNAL_SATURATE(x, max) ( ((x) > max) ? max : ( (-(x) > max) ? (-max) : (x) ) );
#endif

#ifndef CANARD_INTERNAL_SATURATE_UNSIGNED
#define CANARD_INTERNAL_SATURATE_UNSIGNED(x, max) ( ((x) > max) ? max : (x) );
#endif

#define CANARD_INTERNAL_ENABLE_TAO  ((uint8_t) 1)
#define CANARD_INTERNAL_DISABLE_TAO ((uint8_t) 0)

#if defined(__GNUC__)
# define CANARD_MAYBE_UNUSED(x) x __attribute__((unused))
#else
# define CANARD_MAYBE_UNUSED(x) x
#endif

/**
  * @brief homeautomation_Environment_encode_internal
  * @param source : pointer to source data struct
  * @param msg_buf: pointer to msg storage
  * @param offset: bit offset to msg storage
  * @param root_item: for detecting if TAO should be used
  * @retval returns offset
  */
uint32_t homeautomation_Environment_encode_internal(homeautomation_Environment* source,
  void* msg_buf,
  uint32_t offset,
  uint8_t CANARD_MAYBE_UNUSED(root_item))
{
    source->humidity_valid = CANARD_INTERNAL_SATURATE_UNSIGNED(source->humidity_valid, 1)
    canardEncodeScalar(msg_buf, offset, 1, (void*)&source->humidity_valid); // 1
    offset += 1;

    source->pressure_valid = CANARD_INTERNAL_SATURATE_UNSIGNED(source->pressure_valid, 1)
    canardEncodeScalar(msg_buf, offset, 1, (void*)&source->pressure_valid); // 1
    offset += 1;

    source->temperature = CANARD_INTERNAL_SATURATE(source->temperature, 262143)
    canardEncodeScalar(msg_buf, offset, 19, (void*)&source->temperature); // 262143
    offset += 19;

    source->humidity = CANARD_INTERNAL_SATURATE_UNSIGNED(source->humidity, 131071)
    canardEncodeScalar(msg_buf, offset, 17, (void*)&source->humidity); // 131071
    offset += 17;

    source->pressure = CANARD_INTERNAL_SATURATE_UNSIGNED(source->pressure, 262143)
    canardEncodeScalar(msg_buf, offset, 18, (void*)&source->pressure); // 262143
    offset += 18;

    return offset;
}

/**
  * @brief homeautomation_Environment_encode
  * @param source : Pointer to source data struct
  * @param msg_buf: Pointer to msg storage
  * @retval returns message length as bytes
  */
uint32_t homeautomation_Environment_encode(homeautomation_Environment* source, void* msg_buf)
{
    uint32_t offset = 0;

    offset = homeautomation_Environment_encode_internal(source, msg_buf, offset, 1);

    return (offset + 7 ) / 8;
}

/**
  * @brief homeautomation_Environment_decode_internal
  * @param transfer: Pointer to CanardRxTransfer transfer
  * @param payload_len: Payload message length
  * @param dest: Pointer to destination struct
  * @param dyn_arr_buf: NULL or Pointer to memory storage to be used for dynamic arrays
  *                     homeautomation_Environment dyn memory will point to dyn_arr_buf memory.
  *                     NULL will ignore dynamic arrays decoding.
  * @param offset: Call with 0, bit offset to msg storage
  * @param tao: is tail array optimization used
  * @retval offset or ERROR value if < 0
  */
int32_t homeautomation_Environment_decode_internal(
  const CanardRxTransfer* transfer,
  uint16_t CANARD_MAYBE_UNUSED(payload_len),
  homeautomation_Environment* dest,
  uint8_t** CANARD_MAYBE_UNUSED(dyn_arr_buf),
  int32_t offset,
  uint8_t CANARD_MAYBE_UNUSED(tao))
{
    int32_t ret = 0;

    ret = canardDecodeScalar(transfer, offset, 1, false, (void*)&dest->humidity_valid);
    if (ret != 1)
    {
        goto homeautomation_Environment_error_exit;
    }
    offset += 1;

    ret = canardDecodeScalar(transfer, offset, 1, false, (void*)&dest->pressure_valid);
    if (ret != 1)
    {
        goto homeautomation_Environment_error_exit;
    }
    offset += 1;

    ret = canardDecodeScalar(transfer, offset, 19, true, (void*)&dest->temperature);
    if (ret != 19)
    {
        goto homeautomation_Environment_error_exit;
    }
    offset += 19;

    ret = canardDecodeScalar(transfer, offset, 17, false, (void*)&dest->humidity);
    if (ret != 17)
    {
        goto homeautomation_Environment_error_exit;
    }
    offset += 17;

    ret = canardDecodeScalar(transfer, offset, 18, false, (void*)&dest->pressure);
    if (ret != 18)
    {
        goto homeautomation_Environment_error_exit;
    }
    offset += 18;
    return offset;

homeautomation_Environment_error_exit:
    if (ret < 0)
    {
        return ret;
    }
    else
    {
        return -CANARD_ERROR_INTERNAL;
    }
}

/**
  * @brief homeautomation_Environment_decode
  * @param transfer: Pointer to CanardRxTransfer transfer
  * @param payload_len: Payload message length
  * @param dest: Pointer to destination struct
  * @param dyn_arr_buf: NULL or Pointer to memory storage to be used for dynamic arrays
  *                     homeautomation_Environment dyn memory will point to dyn_arr_buf memory.
  *                     NULL will ignore dynamic arrays decoding.
  * @retval offset or ERROR value if < 0
  */
int32_t homeautomation_Environment_decode(const CanardRxTransfer* transfer,
  uint16_t payload_len,
  homeautomation_Environment* dest,
  uint8_t** dyn_arr_buf)
{
    const int32_t offset = 0;
    int32_t ret = 0;

    /* Backward compatibility support for removing TAO
     *  - first try to decode with TAO DISABLED
     *  - if it fails fall back to TAO ENABLED
     */
    uint8_t tao = CANARD_INTERNAL_DISABLE_TAO;

    while (1)
    {
        // Clear the destination struct
        for (uint32_t c = 0; c < sizeof(homeautomation_Environment); c++)
        {
            ((uint8_t*)dest)[c] = 0x00;
        }

        ret = homeautomation_Environment_decode_internal(transfer, payload_len, dest, dyn_arr_buf, offset, tao);

        if (ret >= 0)
        {
            break;
        }

        if (tao == CANARD_INTERNAL_ENABLE_TAO)
        {
            break;
        }
        tao = CANARD_INTERNAL_ENABLE_TAO;
    }

    return ret;
}
