/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 */

#ifndef __HOMEAUTOMATION_MOTION
#define __HOMEAUTOMATION_MOTION

#include <stdint.h>
#include "canard.h"

#ifdef __cplusplus
extern "C"
{
#endif

/******************************* Source text **********************************
uint8 triggered
******************************************************************************/

/********************* DSDL signature source definition ***********************
homeautomation.Motion
saturated uint8 triggered
******************************************************************************/

#define HOMEAUTOMATION_MOTION_ID                           20011
#define HOMEAUTOMATION_MOTION_NAME                         "homeautomation.Motion"
#define HOMEAUTOMATION_MOTION_SIGNATURE                    (0x27E5F95F100138E3ULL)

#define HOMEAUTOMATION_MOTION_MAX_SIZE                     ((8 + 7)/8)

// Constants

typedef struct
{
    // FieldTypes
    uint8_t    triggered;                     // bit len 8

} homeautomation_Motion;

extern
uint32_t homeautomation_Motion_encode(homeautomation_Motion* source, void* msg_buf);

extern
int32_t homeautomation_Motion_decode(const CanardRxTransfer* transfer, uint16_t payload_len, homeautomation_Motion* dest, uint8_t** dyn_arr_buf);

extern
uint32_t homeautomation_Motion_encode_internal(homeautomation_Motion* source, void* msg_buf, uint32_t offset, uint8_t root_item);

extern
int32_t homeautomation_Motion_decode_internal(const CanardRxTransfer* transfer, uint16_t payload_len, homeautomation_Motion* dest, uint8_t** dyn_arr_buf, int32_t offset, uint8_t tao);

#ifdef __cplusplus
} // extern "C"
#endif
#endif // __HOMEAUTOMATION_MOTION