/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/matthias/Projekte/heizungssteuerung/dsdl/homeautomation/20006.Time.uavcan
 */

#ifndef __HOMEAUTOMATION_TIME
#define __HOMEAUTOMATION_TIME

#include <stdint.h>
#include "canard.h"

#ifdef __cplusplus
extern "C"
{
#endif

/******************************* Source text **********************************
uint56 usec
bool daylight
******************************************************************************/

/********************* DSDL signature source definition ***********************
homeautomation.Time
saturated uint56 usec
saturated bool daylight
******************************************************************************/

#define HOMEAUTOMATION_TIME_ID                             20006
#define HOMEAUTOMATION_TIME_NAME                           "homeautomation.Time"
#define HOMEAUTOMATION_TIME_SIGNATURE                      (0x50A53CA677DC1C85ULL)

#define HOMEAUTOMATION_TIME_MAX_SIZE                       ((57 + 7)/8)

// Constants

typedef struct
{
    // FieldTypes
    uint64_t   usec;                          // bit len 56
    bool       daylight;                      // bit len 1

} homeautomation_Time;

extern
uint32_t homeautomation_Time_encode(homeautomation_Time* source, void* msg_buf);

extern
int32_t homeautomation_Time_decode(const CanardRxTransfer* transfer, uint16_t payload_len, homeautomation_Time* dest, uint8_t** dyn_arr_buf);

extern
uint32_t homeautomation_Time_encode_internal(homeautomation_Time* source, void* msg_buf, uint32_t offset, uint8_t root_item);

extern
int32_t homeautomation_Time_decode_internal(const CanardRxTransfer* transfer, uint16_t payload_len, homeautomation_Time* dest, uint8_t** dyn_arr_buf, int32_t offset, uint8_t tao);

#ifdef __cplusplus
} // extern "C"
#endif
#endif // __HOMEAUTOMATION_TIME